### ISSUE TITLE
Ajouter le format pdf

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/dcat-server#12]
![image](https://user-images.githubusercontent.com/16936198/195364682-4004d837-e0fb-45b5-92bc-9286de3de4b9.png)

**Comment by Mouzzi-C** [comment]
receter avec @Mouzzi-C et @leodarengosse

**Comment by leodarengosse** [comment]
Non recettable actuellement à cause du problème de moissonnage de datagouv

**Comment by leodarengosse** [comment]
En recettant le dcat dockerisé, je constate que le format pdf est bien récupéré et l'url de téléchargement proposée 
![image](https://github.com/isogeo/dcat-server/assets/16936198/669efd36-9160-48c4-9514-fc7747022a03)

**Comment by jgrosmaire** [comment]
@leodarengosse toujours pas recettable ?

**Comment by leodarengosse** [comment]
Le format pdf est bien remonté dans datagouv pour la [fiche](https://app.isogeo.com/groups/a98b04d94b844f1e8362103046fdc32e/resources/2c83acdc91444502b99eb58e14a34c54/resources) correspondant au commentaire précédent cf [fiche sur demo.data.gouv](https://demo.data.gouv.fr/fr/admin/dataset/62edb3858f4192aef13e8678/)

![image](https://github.com/isogeo/dcat-server/assets/16936198/224e3b7f-c35e-439b-b14e-868a4628c702)

Je valide donc ce ticket
