### ISSUE TITLE
La date de dernière mise à jour de la ressource n'est plus remontée

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/dcat-server#13]
Il faudrait rajouter le champ issued au niveau de la Dataset

Par exemple, pour ce [DCAT](https://dcat.isogeo.com/0bd17a2a330842c68ec4a412d1df6824/AiCyPK6W8fg012l-vHV0s5tPry5b0) et la fiche Cartographie des points d'adresse , il faudrait qu'un champ "issued" contiennent la date du 27 février 2023 après accrualPeriodicity et avant les distributions.

![image](https://user-images.githubusercontent.com/16936198/229452120-5ffa2fbf-1cae-4390-aad2-01c8ae6c5ed7.png)

**Comment by jgrosmaire** [comment]
Faut-il aussi l'enlever des distributions ? @leodarengosse 
![image](https://user-images.githubusercontent.com/66669475/229778930-290da66c-d3cf-49e5-b0ba-5aaa288ee22b.png)

**Comment by leodarengosse** [comment]
Réponse du support data.gouv

> Bonjour,
> 
> Nous récupérons les informations de création (DCT.issued) et de dernière modification (DCT.modified) au niveau du Dataset et de la Distribution (voir mapping décrit ici : https://doc.data.gouv.fr/moissonnage/dcat/).
> Pour la date de dernière mise à jour affichée sur la fiche du jeu de données, il s'agit implicitement de la date de dernière mise à jour des ressources. Nous regardons donc la date de dernière modification (DCT.modified) la plus récente parmi toutes les ressources. La date de modification rattachée au jeu de données n'est pas affichée sur le front, mais est tout de même disponible par API.
> 
> Je vous invite donc à renseigner les informations de création et de modification au moins au niveau de chacune des Distributions si vous avez les informations pour permettre à l'usager d'avoir un maximum d'informations pertinentes.
> 
> Je m'excuse du manque de clareté sur le réponses précédentes, et espère que c'est plus clair maintenant.

J'en conclus qu'il faut conserver le champ issued sur chaque distribution et que c'est la plus récente qui permet de renseigner la date de dernière modification de la ressource.

**Comment by leodarengosse** [comment]
qa-dcat-server.azurewebsites.net

**Comment by jgrosmaire** [comment]
C'est en prod

**Comment by leodarengosse** [comment]
@jgrosmaire c'est bien en QA mais pas en Prod, est-ce que tu peux mettre en Prod comme ça je pourrais voir si la date est bien moissonnée stp ?

**Comment by leodarengosse** [comment]
Cette fois c'est bon, on a bien la date du 27 février ! [https://www.data.gouv.fr/fr/datasets/cartographie-des-points-adresse-de-lorient-agglomeration/#/information](https://www.data.gouv.fr/fr/datasets/cartographie-des-points-adresse-de-lorient-agglomeration/#/information)
