### ISSUE TITLE
Permettre le téléchargement de fichier GeoJSON en Lambert-93 ou convertir le système de coordonnées à du WGS 84

### ISSUE THREAD

**Issue by Mouzzi-C** [isogeo/dcat-server#5]
## Contexte
Demande d'aide d'une cliente afin de convertir son projet de Lambert-93 à WGS 84 afin de répondre aux prérequis de téléchargement de la donnée sur data.gouv

L'idée est de déterminer quel serait la meilleure option entre la publication sur data.gouv d'un GeoJSON en Lambert-93 ou la conversion de ce dernier en WGS 84. 

## Méthodes de modification du système de coordonnées dans Arcmap et Arcgis Pro
1. ArcGIS Desktop : 
  * Modification du système de coordonnées en passant par ArcCatalog. 
  * L'outil "définir une projection" ne permet pas de modifier une projection mais uniquement d'en ajouter une si la donnée n'en a pas.
  * L'utilisation de l'outil "projeter" permet la création d'une nouvelle donnée pour ensuite l'ajouter à la base de donnée et remplacer la version en Lambert-93. Il faut ensuite remplacé la donnée dans le projet ArcMap utilisé pour publier le service.
 2.  ArcGIS Pro : Modification de la donnée en utilisant l'outil "définir une projection" pour ensuite l'ajouter à la base de donnée et remplacer la version en Lambert-93. Il faut ensuite remplacé la donnée dans le projet ArcMap utilisé pour publier le service.

## Ajout à la carte Geojson
Les tests ont été réalisé avec avec des données téléchargées à partir de l'OC ainsi que des données exportées dans QGIS. 

* QGIS : Fonctionne sans problème, quelque soit système de coordonnées de la donnée.
* ArcMap/ArcGIS Pro : Nécessite l'ajout de l'extension "data interoperability" afin de visualiser ce type de format.

![image (2)](https://user-images.githubusercontent.com/63340073/154099290-31de3f90-a689-4fb8-961a-7aed6f1ac20b.png)

![image (1)](https://user-images.githubusercontent.com/63340073/154099236-f2234200-a4c8-4db0-8134-4b7ec0356994.png)

**Comment by jgrosmaire** [comment]
Finalement, après vérification du code, et du ticket où on avait spécifié les services dans le serveur dcat (https://github.com/isogeo/geodataprocess-api/issues/65), ce qui est mentionné est déjà implémenté.

![image](https://user-images.githubusercontent.com/66669475/154722304-f561e2af-8b46-45db-9213-448f7030a231.png)

On obtient un lien de téléchargement en geojson pour les EFS ayant comme projection par défaut le WGS84 et les WFS ayant comme format de sortie le geojson.
