### ISSUE TITLE
Problème de chargement du DCAT du Loiret et de la Normandie

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/dcat-server#6]
# Contexte 

Les serveurs DCAT suivants ne peuvent pas être moissonnés par data.gouv : 

- Loiret : https://dcat.isogeo.com/1742fb942d7b4756b9778c3b3cbc992e/HWglEr-z4Bry_rKQOTINX9gAH4Yu0
- Normandie : https://dcat.isogeo.com/117146d833e7419b90b7a3390530e52b/xgwHHRasDEucGqtwQUaGEE8ys55j0

Cela peut être causé par les raisons suivantes : 

- Récupération du format des fichiers téléversés
- Analyse des services via l'API GeoData

# Solutions

## Solutions temporaires

- [x] Supprimer la récupération du format du fichier téléversé le temps de régler l'ajout dans l'API ([#102](https://github.com/isogeo/isogeo-api/issues/102))
- [x] Supprimer l'analyse de EFS qui sont forcément en 2154 pour le Loiret
- [x] Augmenter la limite de pagination de la requête Search de l'API

## Solutions long-terme

Il serait possible de : 

- Mettre en place un cache

#### Redis

Il est possible de mettre en place un [composant Azure de cache](https://docs.microsoft.com/fr-fr/azure/azure-cache-for-redis/cache-nodejs-get-started) pour utiliser redis dans le serveur dcat qui permettrait de gérer le cache. Le composant semble cependant critiqué pour être particulièrement lent et nécessiterait également des coûts en plus.  L'avantage de l'utilisation de redis est le fait que les clefs ne sont pas stockées dans la webapp directement et qu'il est facile de gérer des dates d'expiration pour les différentes données de cache. https://www.npmjs.com/package/redis 

#### Cache local dans la WebApp

Il existe un certains nombres de libraires de cache maintenues dans npm  : https://www.npmjs.com/package/node-cache

### Questionnement sur le cache

* Comment gérer les données sans liens de téléchargement (pas de projection disponible, service pas disponible pour le moment) ? 
  * Faut-il les requêter plus souvent en imaginant pas exemple dans le cas d'un service pas disponible qu'il n'est pas disponible pour le moment seulement ou faut-il supposer que c'est un service cassé et donc le requêter moins souvent ?

**Comment by jgrosmaire** [comment]
Choses à faire : 

* retirer le cache
* retirer la vérification des EFS

**Comment by leodarengosse** [comment]
Corrigé en supprimant la vérification des EFS
